BEGIN;

CREATE TABLE Posts (
  id BINARY(16) NOT NULL,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  author BINARY(16) NOT NULL,
  
  PRIMARY KEY (id),
  FOREIGN KEY (author) REFERENCES Authors(id) ON DELETE CASCADE
);

COMMIT;